package eu.janinko.andaria.editor;

import eu.janinko.Andaria.ultimasdk.files.graphics.Color;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author janinko
 */
public class HueEdit extends javax.swing.JFrame {
	private HueEditor huedit = new HueEditor();
	private int hueId;
	private int selected;

	/**
	 * Creates new form HueEdit
	 */
	public HueEdit() {
		try {
			huedit.init();
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents();
		paletaImg.setIcon(new ImageIcon(huedit.getPallete()));
	}

	private void showHue(){
		ImageIcon icon = new ImageIcon(huedit.getHueImage(hueId));
		hueLabel.setIcon(icon);
		try {
			ImageIcon icon2 = new ImageIcon(huedit.getColoredItem(hueId, 50521));
			img1.setIcon(icon2);
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			ImageIcon icon2 = new ImageIcon(huedit.getColoredItem(hueId, 50522));
			img2.setIcon(icon2);
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
		try {
			ImageIcon icon2 = new ImageIcon(huedit.getColoredItem(hueId, 50523));
			img3.setIcon(icon2);
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void colorSelected(){
		Color c = huedit.getHue(hueId).getColor(selected);
		redSlider.setValue(c.get5Red());
		greenSlider.setValue(c.get5Green());
		blueSlider.setValue(c.get5Blue());
	}

	private void sliderChange(){
		BufferedImage img = huedit.getColorImage(redSlider.getValue(), greenSlider.getValue(), blueSlider.getValue());
		ImageIcon icon = new ImageIcon(img);
		colorLabel.setIcon(icon);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paleta = new javax.swing.JFrame();
        paletaImg = new javax.swing.JLabel();
        hueLabel = new javax.swing.JLabel();
        hueNumber = new javax.swing.JTextField();
        showButton = new javax.swing.JButton();
        redSlider = new javax.swing.JSlider();
        greenSlider = new javax.swing.JSlider();
        blueSlider = new javax.swing.JSlider();
        redText = new javax.swing.JTextField();
        greenText = new javax.swing.JTextField();
        blueText = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        hueName = new javax.swing.JLabel();
        copyText = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        paleta.setMinimumSize(new java.awt.Dimension(1620, 1010));

        paletaImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paletaImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paletaLayout = new javax.swing.GroupLayout(paleta.getContentPane());
        paleta.getContentPane().setLayout(paletaLayout);
        paletaLayout.setHorizontalGroup(
            paletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paletaImg, javax.swing.GroupLayout.DEFAULT_SIZE, 1596, Short.MAX_VALUE)
                .addContainerGap())
        );
        paletaLayout.setVerticalGroup(
            paletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paletaImg, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hueLabelMouseClicked(evt);
            }
        });

        hueNumber.setText("10");
        hueNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hueNumberActionPerformed(evt);
            }
        });

        showButton.setText("show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        redSlider.setMaximum(31);
        redSlider.setPaintLabels(true);
        redSlider.setValue(0);
        redSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redSliderStateChanged(evt);
            }
        });

        greenSlider.setMaximum(31);
        greenSlider.setValue(0);
        greenSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenSliderStateChanged(evt);
            }
        });

        blueSlider.setMaximum(31);
        blueSlider.setValue(0);
        blueSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueSliderStateChanged(evt);
            }
        });

        redText.setText("0");
        redText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTextActionPerformed(evt);
            }
        });
        redText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                redTextKeyReleased(evt);
            }
        });

        greenText.setText("0");
        greenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenTextActionPerformed(evt);
            }
        });

        blueText.setText("0");

        setButton.setText("set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jButton4.setText("CopyFrom");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Paleta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hueNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hueName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(blueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(blueText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(greenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(greenText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(redSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generateButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(copyText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hueNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showButton)
                    .addComponent(hueName)
                    .addComponent(copyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(redText)
                            .addComponent(redSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(greenText)
                            .addComponent(greenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(blueText)
                            .addComponent(blueSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
      hueId = Integer.parseInt(hueNumber.getText());
		hueName.setText(huedit.getHue(hueId).getName());
		showHue();
   }//GEN-LAST:event_showButtonActionPerformed

   private void hueNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hueNumberActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_hueNumberActionPerformed

   private void hueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hueLabelMouseClicked
      Point p = evt.getPoint();
		selected = huedit.getHueOn(p.x);
		colorSelected();
   }//GEN-LAST:event_hueLabelMouseClicked

   private void greenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenTextActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_greenTextActionPerformed

   private void redSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redSliderStateChanged
      int value = redSlider.getValue();
		redText.setText(Integer.toString(value));
		sliderChange();
   }//GEN-LAST:event_redSliderStateChanged

   private void redTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTextActionPerformed

   }//GEN-LAST:event_redTextActionPerformed

   private void redTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_redTextKeyReleased

   }//GEN-LAST:event_redTextKeyReleased

   private void greenSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenSliderStateChanged
      int value = greenSlider.getValue();
		greenText.setText(Integer.toString(value));
		sliderChange();
   }//GEN-LAST:event_greenSliderStateChanged

   private void blueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueSliderStateChanged
      int value = blueSlider.getValue();
		blueText.setText(Integer.toString(value));
		sliderChange();
   }//GEN-LAST:event_blueSliderStateChanged

   private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
      huedit.setHue(hueId, selected, redSlider.getValue(), greenSlider.getValue(), blueSlider.getValue());
		showHue();
   }//GEN-LAST:event_setButtonActionPerformed

   private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
		try {
			huedit.generate(hueId);
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
   }//GEN-LAST:event_generateButtonActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		int from = Integer.parseInt(copyText.getText());
		huedit.copy(from, hueId);
		showHue();
   }//GEN-LAST:event_jButton4ActionPerformed

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		try {
			huedit.save();
		} catch (IOException ex) {
			Logger.getLogger(HueEdit.class.getName()).log(Level.SEVERE, null, ex);
		}
   }//GEN-LAST:event_jButton5ActionPerformed

   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      System.out.println("paleta: " + paleta);
		paleta.setVisible(true);
   }//GEN-LAST:event_jButton6ActionPerformed

    private void paletaImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paletaImgMouseClicked
		Point p = evt.getPoint();
		int x = p.x / 32;
		int y = p.y / 16;
		hueId = x * 60 + y + 1;
		hueNumber.setText(Integer.toString(hueId));
		hueName.setText(huedit.getHue(hueId).getName());
		showHue();
    }//GEN-LAST:event_paletaImgMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HueEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HueEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HueEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HueEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HueEdit().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider blueSlider;
    private javax.swing.JTextField blueText;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField copyText;
    private javax.swing.JButton generateButton;
    private javax.swing.JSlider greenSlider;
    private javax.swing.JTextField greenText;
    private javax.swing.JLabel hueLabel;
    private javax.swing.JLabel hueName;
    private javax.swing.JTextField hueNumber;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame paleta;
    private javax.swing.JLabel paletaImg;
    private javax.swing.JSlider redSlider;
    private javax.swing.JTextField redText;
    private javax.swing.JButton setButton;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
